trigger:
  batch: true
  branches:
    include:
      - "master"

variables:
  - name: buildConfiguration
    value: 'release'
  - group: RELEASE Management Resources

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: DASD-9692-comment-on-prs
    endpoint: SkillsFundingAgency

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml
  - template: pipeline-templates/job/dacpac-build.yml