CREATE VIEW [dbo].[ons_staging_view]
AS SELECT [placeid] [Place_Name_Identifier]
,[place20cd] [Place_Name_Code]
,[place20nm] [Place_Name]
,[splitind] [Split_Place_Name_Indicator]
,[descnm] [Place_Name_Description]
,[ctyhistnm] [Historic_County_Name]
,[cty61nm] [1961_County_Name]
,[cty91nm] [1991_County_Name]
,[ctyltnm] [Lieutenancy_County_Name]
,[ctry20nm] [Country_Name]
,[cty20cd] [County_Code]
,[cty20nm] [County_Name]
,[lad61nm] [1961_Local_Authority_District_Name]
,[lad61desc] [1961_Local_Authority_District_Description]
,[lad91nm] [1991_Local_Authority_District_Name]
,[lad91desc] [1991_Local_Authority_District_Description]
,[lad20cd] [Local_Authority_District_Code]
,[lad20nm] [Local_Authority_District_Name]
,[lad20desc] [Local_Authority_District_Description]
,[ced18cd] [County_Electoral_Division_Code]
,[wd19cd] [Electoral_Ward/Division_Code]
,[par20cd] [Civil_Parish_Code]
,[hlth12cd] [Strategic_Health_Authority_Code]
,[hlth12nm] [Strategic_Health_Authority_Name]
,[regd20cd] [Registration_District_Code]
,[regd20nm] [Registration_District_Name]
,[rgn20cd] [Region_Code]
,[rgn20nm] [Region_Name]
,[npark19cd] [National_Park_Code]
,[npark19nm] [National_Park_Name]
,[bua11cd] [Built-up_Area_Code]
,[pcon20cd] [Westminster_Parliamentary_Constituency_Code]
,[pcon20nm] [Westminster_Parliamentary_Constituency_Name]
,[eer20cd] [European_Electoral_Region_Code]
,[eer20nm] [European_Electoral_Region_Name]
,[pfa20cd] [Police_Force_Area_Code]
,[pfa20nm] [Police_Force_Area_Name]
,[gridgb1m] [1_metre_grid_reference]
,[gridgb1e] [1_metre_Easting_grid_reference]
,[gridgb1n] [1_metre_Northing_grid_reference]
,[grid1km] [1_kilometre_grid_square_reference]
,[lat] [Latitude]
,[long] [Longitude]
FROM [dbo].[ons_staging]

GO